trainset:
  name: flyingthings3d
  root_dir: /data/processed_flyingthings3d
  split: train
  n_workers: 4
  drop_last: true
  full: false

  augmentation:
    enabled: false
    color_jitter:
      enabled: false
    random_horizontal_flip:
      enabled: false
    random_vertical_flip:
      enabled: false
    random_crop:
      enabled: false
    random_scale:
      enabled: false

valset:
  name: flyingthings3d
  root_dir: /data/processed_flyingthings3d
  split: val
  n_workers: 4
  full: false

  augmentation:
    enabled: false

model:
  name: pretrain
  height: 256
  width: 448
  stride_h: [2, 2, 2, 2, 2, 2]
  stride_w: [2, 2, 2, 2, 2, 2]
  freeze_bn: false
  batch_size: 64

  pwc2d:
    norm:
      feature_pyramid: batch_norm
      flow_estimator: null
      context_network: null
    max_displacement: 4

  pwc3d:
    norm:
      feature_pyramid: batch_norm
      correlation: null
      flow_estimator: null
    k: 16
    kernel_size: [10, 20]

  loss2d:
    level_weights: [8, 4, 2, 1, 0.5]
    order: l2

  loss3d:
    level_weights: [8, 4, 2, 1, 0.5]
    order: l2


training:
  opt: adamw
  momentum: 0.9
  weight_decay: 0.00001
  grad_max_norm: 20
  accum_iter: 1

  sched: cosine
  epochs: 800
  lr_2d: 0.0005 # LR for 2D branch
  lr_3d: 0.001 # LR for 3D branch
  min_lr: 0.00001
  warmup_lr: 0.00001
  warmup_epochs: 2
  cooldown_epochs: 0

log:
  dir: ./experiment
  run_name: pretrain
  save_ckpt: true
  save_scalar_summary: true
  save_ckpt_every_n_epochs: 1
  save_summary_every_n_steps: 100

ckpt:
  path: null
  save_path: ./checkpoints
  resume: false

val_interval: 10
gpu: 1
port: random # for multi-gpu training
amp: false
debug: false
sync_bn: true
